import { ClientEntity } from '../../domain/entities/client.entity';

export class ClientMapper {
  static toDomain(raw: any): ClientEntity {
    return ClientEntity.restore({
      id: raw.id,
      cnpj: raw.cnpj,
      nome: raw.nome,
      municipio: raw.municipio,
      estado: raw.estado,
      endereco: raw.endereco,
      clienteLivre: raw.cliente_livre,
      microGerador: raw.micro_gerador,
      nivelTensao: raw.nivel_tensao,
      classePrincipal: raw.classe_principal,
      subclasse: raw.subclasse,
      potencia: raw.potencia,
      tipoTarifa: raw.tipo_tarifa,
      tipoCliente: raw.tipo_cliente,
      dataDe: raw.data_de,
      dataAte: raw.data_ate,
      contratoAtivo: raw.contrato_ativo,
      telFixo: raw.tel_fixo,
      telMovel: raw.tel_movel,
      email: raw.email,
      cnae: raw.cnae,
      tipoPerfil: raw.tipo_perfil,
      aiRationale: raw.ai_rationale,
      sourceBatch: raw.source_batch,
      isDeleted: raw.is_deleted ?? false,
      lat: raw.lat,
      lng: raw.lng,
      createdAt: raw.created_at,
      updatedAt: raw.updated_at,
    });
  }

  static toPersistence(entity: ClientEntity): any {
    return {
      id: entity.id,
      cnpj: entity.cnpj ?? null,
      nome: entity.nome,
      municipio: entity.municipio ?? null,
      estado: entity.estado ?? null,
      endereco: entity.endereco ?? null,
      cliente_livre: entity.clienteLivre ?? null,
      micro_gerador: entity.microGerador ?? null,
      nivel_tensao: entity.nivelTensao ?? null,
      classe_principal: entity.classePrincipal ?? null,
      subclasse: entity.subclasse ?? null,
      potencia: entity.potencia ?? null,
      tipo_tarifa: entity.tipoTarifa ?? null,
      tipo_cliente: entity.tipoCliente ?? null,
      data_de: entity.dataDe ?? null,
      data_ate: entity.dataAte ?? null,
      contrato_ativo: entity.contratoAtivo ?? null,
      tel_fixo: entity.telFixo ?? null,
      tel_movel: entity.telMovel ?? null,
      email: entity.email ?? null,
      cnae: entity.cnae ?? null,
      tipo_perfil: entity.tipoPerfil ?? null,
      ai_rationale: entity.aiRationale ?? null,
      source_batch: entity.sourceBatch ?? null,
      is_deleted: entity.isDeleted,
      lat: entity.lat ?? null,
      lng: entity.lng ?? null,
    };
  }

  static toResponse(entity: ClientEntity): any {
    return {
      id: entity.id,
      cnpj: entity.cnpj,
      name: entity.nome,
      company: entity.nome,
      municipio: entity.municipio,
      state: entity.estado,
      endereco: entity.endereco,
      clienteLivre: entity.clienteLivre,
      microGerador: entity.microGerador,
      nivelTensao: entity.nivelTensao,
      classePrincipal: entity.classePrincipal,
      industry: entity.classePrincipal,
      subclasse: entity.subclasse,
      potencia: entity.potencia,
      tipoTarifa: entity.tipoTarifa,
      tariffType: entity.tipoTarifa,
      tipoCliente: entity.tipoCliente,
      dataDe: entity.dataDe,
      dataAte: entity.dataAte,
      contratoAtivo: entity.contratoAtivo,
      telFixo: entity.telFixo,
      telMovel: entity.telMovel,
      email: entity.email ?? '',
      cnae: entity.cnae,
      profile: entity.tipoPerfil,
      segment: entity.tipoPerfil ?? 'Não Segmentado',
      aiRationale: entity.aiRationale,
      sourceBatch: entity.sourceBatch,
      isDeleted: entity.isDeleted,
      lat: entity.lat,
      lng: entity.lng,
      role: 'Decisor',
      employees: 0,
      createdAt: entity.createdAt,
    };
  }
}
